# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do

desc "Description of what the lane does"
lane :custom_lane do
# add actions here: https://docs.fastlane.tools/actions
end


desc "Take screenshots"
    lane :screenshot do
    capture_screenshots
    upload_to_app_store
end


desc 'Setup Apple Certificates'
lane :certificates do
    match(type: "appstore", app_identifier: "com.mi.all", readonly: true)
end



   lane :beta do
    
    build_app(scheme: "FastlaneBasics")
      increment_build_number
        pilot(
            ipa: "FastlaneBasics.ipa",
            skip_submission: true,
            itc_provider:"7224G6JACN",
            skip_waiting_for_build_processing: true
        )
    end

    lane :release do
        increment_build_number
        build_app(scheme: "FastlaneBasics")
        upload_to_app_store                  # upload your app to App Store Connect
    end


    increment_build_number                   # increment build number


end
