# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end


  desc "Take screenshots"
 lane :screenshot do
  capture_screenshots
  frame_screenshots(white: true)
  upload_to_app_store
 end


 desc 'Setup Apple Certificates'
  lane :certificates do
    match(type: "appstore", app_identifier: "com.mi.all", readonly: true)
  end

lane :beta do
   
  sync_code_signing(type: "appstore")    # see code signing guide for more information
  build_app(scheme: "FastlaneBasics")
  upload_to_testflight
  slack(message: "Successfully distributed a new beta build")

end

end
